#! /usr/bin/env bash

# Environment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10
bspc config split_ratio          0.50

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# BSPWM coloring
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#1e1e1e"
bspc config focused_border_color        "#5e81ac"
bspc config presel_feedback_color       "#5e81ac"
bspc config urgent_border_color         "#dd2727"

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

# 2 > web
bspc rule -a Brave-browser desktop='^2' follow=on focus=on

# 3 > files
declare -a files=(Pcmanfm transmission)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

# 4 > code
declare -a code=(Geany code-oss)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

# 5 > office and docs
declare -a office=(Atril)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done

# 6 > Communication
bspc rule -a TelegramDesktop desktop='^6' follow=on focus=on

# 7 > Music
declare -a music=(sayonara Audacity)
for i in ${music[@]}; do
  bspc rule -a $i desktop='^7' follow=on focus=on; done

# 8 > Media
declare -a media=(Mplayer mpv)
for i in ${media[@]}; do
  bspc rule -a $i desktop='^8' follow=on focus=on; done

# 9 > Images
bspc rule -a Viewnior desktop='^9' follow=on focus=on

# floating applications
bspc rule -a feh state=floating

# kill if already running
killall -9 sxhkd dunst ksuperkey xfce4-power-manager

# launch polybar
$HOME/.config/polybar/launch.sh &

# Launch xsettingsd daemon
xsettingsd &

# run keybindings daemon
sxhkd -c $HOME/.config/bspwm/sxhkd/sxhkdrc &

# restore wallpaper
bash $HOME/.fehbg

# start picom
picom --config $HOME/.config/bspwm/picom/picom.conf &
